id: P008094
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1017401
  title: གསུང་འབུམ། འཇིགས་མེད་དམ་ཆོས་རྒྱ་མཚོ།
  author: ''
  volumes:
    14121f340f0147899d3e94af180eba49:
      image_group_id: I00EGS1017403
      title: ''
      volume_number: 1
      total_pages: 706
    b2055ac608c145ecbcdbe0426ebcc79a:
      image_group_id: I00EGS1017404
      title: ''
      volume_number: 2
      total_pages: 740
    0744df4563fc482aabf981d043be4729:
      image_group_id: I00EGS1017405
      title: ''
      volume_number: 3
      total_pages: 718
    76af65052ccb4145a5d3d061a92abc8d:
      image_group_id: I00EGS1017406
      title: ''
      volume_number: 4
      total_pages: 710
    6ddd48753608498f9bc3100a71ac76ab:
      image_group_id: I00EGS1017407
      title: ''
      volume_number: 5
      total_pages: 684
    b63701eac8114c78b901812f869f05a5:
      image_group_id: I00EGS1017408
      title: ''
      volume_number: 6
      total_pages: 734
    92996268f2fd462887d88c5d0a8a1535:
      image_group_id: I00EGS1017409
      title: ''
      volume_number: 7
      total_pages: 684
    dae84066f74e4cd19b31b5eb2d9f826d:
      image_group_id: I00EGS1017410
      title: ''
      volume_number: 8
      total_pages: 718
    84d9df95f85b41458c91f73b8a45db96:
      image_group_id: I00EGS1017411
      title: ''
      volume_number: 9
      total_pages: 674
    fd2eb5ca93064b05af479bedc151cf43:
      image_group_id: I00EGS1017412
      title: ''
      volume_number: 10
      total_pages: 716
    46a3c7262cdd4ea0b23f1cdd766776cc:
      image_group_id: I00EGS1017413
      title: ''
      volume_number: 11
      total_pages: 684
    8957248b584c4a269354c1254ad71a43:
      image_group_id: I00EGS1017414
      title: ''
      volume_number: 12
      total_pages: 746
    19b8583ccd104edb8086e23c26091cfc:
      image_group_id: I00EGS1017415
      title: ''
      volume_number: 13
      total_pages: 754
    32e65a21f5dc4eadb3017867681852fd:
      image_group_id: I00EGS1017416
      title: ''
      volume_number: 14
      total_pages: 710
    b937203adc5d4fd5af0d33440519a891:
      image_group_id: I00EGS1017417
      title: ''
      volume_number: 15
      total_pages: 716
ebook_metadata:
  title: གསུང་འབུམ། འཇིགས་མེད་དམ་ཆོས་རྒྱ་མཚོ།
  author: ''
  sku: P008094
  cover: cover.jpg
  layers:
  - pagination
