id: I9D1BDDB6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T23:16:53+00:00'
last_modified: '2022-06-09T04:27:18.838019+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1017401
  title: གསུང་འབུམ། འཇིགས་མེད་དམ་ཆོས་རྒྱ་མཚོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    5AEF:
      image_group_id: I00EGS1017403
      title: Volume 1 of gsung 'bum / 'jigs med dam chos rgya mtsho
      total_pages: 706
      order: 1
      base_file: 5AEF.txt
    '3339':
      image_group_id: I00EGS1017404
      title: Volume 2 of gsung 'bum / 'jigs med dam chos rgya mtsho
      total_pages: 740
      order: 2
      base_file: 3339.txt
    07AA:
      image_group_id: I00EGS1017405
      title: Volume 3 of gsung 'bum / 'jigs med dam chos rgya mtsho
      total_pages: 718
      order: 3
      base_file: 07AA.txt
    '8238':
      image_group_id: I00EGS1017406
      title: Volume 4 of gsung 'bum / 'jigs med dam chos rgya mtsho
      total_pages: 710
      order: 4
      base_file: 8238.txt
    C2DD:
      image_group_id: I00EGS1017407
      title: Volume 5 of gsung 'bum / 'jigs med dam chos rgya mtsho
      total_pages: 684
      order: 5
      base_file: C2DD.txt
    C559:
      image_group_id: I00EGS1017408
      title: Volume 6 of gsung 'bum / 'jigs med dam chos rgya mtsho
      total_pages: 734
      order: 6
      base_file: C559.txt
    AAA7:
      image_group_id: I00EGS1017409
      title: Volume 7 of gsung 'bum / 'jigs med dam chos rgya mtsho
      total_pages: 684
      order: 7
      base_file: AAA7.txt
    '9444':
      image_group_id: I00EGS1017410
      title: Volume 8 of gsung 'bum / 'jigs med dam chos rgya mtsho
      total_pages: 718
      order: 8
      base_file: 9444.txt
    EF91:
      image_group_id: I00EGS1017411
      title: Volume 9 of gsung 'bum / 'jigs med dam chos rgya mtsho
      total_pages: 674
      order: 9
      base_file: EF91.txt
    '8283':
      image_group_id: I00EGS1017412
      title: Volume 10 of gsung 'bum / 'jigs med dam chos rgya mtsho
      total_pages: 716
      order: 10
      base_file: 8283.txt
    A765:
      image_group_id: I00EGS1017413
      title: Volume 11 of gsung 'bum / 'jigs med dam chos rgya mtsho
      total_pages: 684
      order: 11
      base_file: A765.txt
    12D1:
      image_group_id: I00EGS1017414
      title: Volume 12 of gsung 'bum / 'jigs med dam chos rgya mtsho
      total_pages: 746
      order: 12
      base_file: 12D1.txt
    DD49:
      image_group_id: I00EGS1017415
      title: Volume 13 of gsung 'bum / 'jigs med dam chos rgya mtsho
      total_pages: 754
      order: 13
      base_file: DD49.txt
    4B38:
      image_group_id: I00EGS1017416
      title: Volume 14 of gsung 'bum / 'jigs med dam chos rgya mtsho
      total_pages: 710
      order: 14
      base_file: 4B38.txt
    703B:
      image_group_id: I00EGS1017417
      title: Volume 15 of gsung 'bum / 'jigs med dam chos rgya mtsho
      total_pages: 716
      order: 15
      base_file: 703B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
