id: I9D1BDDB6
legacy_id: P008094
ocr_import_info:
  bdrc_scan_id: W00EGS1017401
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T23:10:11'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T13:46:25.690531+00:00'
last_modified: 2022-08-30 22:01:59.430199
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1017401
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1017401
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། འཇིགས་མེད་དམ་ཆོས་རྒྱ་མཚོ།
  author: རྫོང་དཀར་འཇིགས་མེད་དམ་ཆོས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.515042732114892
  ocr_word_median_confidence_index: 0.47999998927116394
quality: null
bases:
  I00EGS1017411:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017411
      total_pages: 674
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I00EGS1017411.txt
    statistics:
      ocr_word_median_confidence_index: 0.4699999988079071
      ocr_word_mean_confidence_index: 0.5109179817871443
    legacy_id: v009
  I00EGS1017410:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017410
      total_pages: 718
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I00EGS1017410.txt
    statistics:
      ocr_word_median_confidence_index: 0.4699999988079071
      ocr_word_mean_confidence_index: 0.5139848346739057
    legacy_id: v008
  I00EGS1017404:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017404
      total_pages: 740
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I00EGS1017404.txt
    statistics:
      ocr_word_median_confidence_index: 0.4099999964237213
      ocr_word_mean_confidence_index: 0.47537957102841294
    legacy_id: v002
  I00EGS1017412:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017412
      total_pages: 716
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I00EGS1017412.txt
    statistics:
      ocr_word_median_confidence_index: 0.5
      ocr_word_mean_confidence_index: 0.5253706443067068
    legacy_id: v010
  I00EGS1017409:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017409
      total_pages: 684
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I00EGS1017409.txt
    statistics:
      ocr_word_median_confidence_index: 0.4699999988079071
      ocr_word_mean_confidence_index: 0.5104388885650075
    legacy_id: v007
  I00EGS1017414:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017414
      total_pages: 746
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I00EGS1017414.txt
    statistics:
      ocr_word_median_confidence_index: 0.6000000238418579
      ocr_word_mean_confidence_index: 0.584162299658395
    legacy_id: v012
  I00EGS1017416:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017416
      total_pages: 710
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I00EGS1017416.txt
    statistics:
      ocr_word_median_confidence_index: 0.5
      ocr_word_mean_confidence_index: 0.5242407171432993
    legacy_id: v014
  I00EGS1017413:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017413
      total_pages: 684
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I00EGS1017413.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.5281532883684473
    legacy_id: v011
  I00EGS1017417:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017417
      total_pages: 716
      volume_number: 15
      volume_pages_bdrc_intro: 2
    order: 15
    base_file: I00EGS1017417.txt
    statistics:
      ocr_word_median_confidence_index: 0.47999998927116394
      ocr_word_mean_confidence_index: 0.5106492857943595
    legacy_id: v015
  I00EGS1017406:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017406
      total_pages: 710
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I00EGS1017406.txt
    statistics:
      ocr_word_median_confidence_index: 0.44999998807907104
      ocr_word_mean_confidence_index: 0.49690807602789355
    legacy_id: v004
  I00EGS1017408:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017408
      total_pages: 734
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I00EGS1017408.txt
    statistics:
      ocr_word_median_confidence_index: 0.49000000953674316
      ocr_word_mean_confidence_index: 0.5215392846600242
    legacy_id: v006
  I00EGS1017405:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017405
      total_pages: 718
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I00EGS1017405.txt
    statistics:
      ocr_word_median_confidence_index: 0.4399999976158142
      ocr_word_mean_confidence_index: 0.4907952778988598
    legacy_id: v003
  I00EGS1017415:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017415
      total_pages: 754
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I00EGS1017415.txt
    statistics:
      ocr_word_median_confidence_index: 0.5899999737739563
      ocr_word_mean_confidence_index: 0.5801536623093534
    legacy_id: v013
  I00EGS1017407:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017407
      total_pages: 684
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I00EGS1017407.txt
    statistics:
      ocr_word_median_confidence_index: 0.4399999976158142
      ocr_word_mean_confidence_index: 0.494368077083297
    legacy_id: v005
  I00EGS1017403:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017403
      total_pages: 706
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00EGS1017403.txt
    statistics:
      ocr_word_median_confidence_index: 0.41999998688697815
      ocr_word_mean_confidence_index: 0.4836366597833938
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
